// Script de TEST temporaire : insère un jeu de participants fictifs varié
// (mélange de tous les cas rencontrés : noms inversés, classement vs étoiles,
// fratries, réciprocités, cours multiples, préférences de prof, cas limites)
// pour valider le comportement de l'algo avec un vrai volume de données.
// A SUPPRIMER après le test (voir /api/test/clear).

const crypto = require('crypto');
const uid = () => crypto.randomBytes(6).toString('hex');

const TEST_STUDENTS = [
  {
    name: "Jean-Yves Lepas",
    age: "45",
    classement: "Non classé",
    niveauEtoile: 3,
    preferenceGroupe: "groupe",
    jouerAvec: ["Dupont Marc"],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Mercredi", heure: "17:00" }, { jour: "Mercredi", heure: "18:00" }],
  },
  {
    name: "Dupont Marc",
    age: "44",
    classement: "Non classé",
    niveauEtoile: 3,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Mercredi", heure: "17:00" }, { jour: "Mercredi", heure: "18:00" }],
  },
  {
    name: "Lepas Sophie",
    age: "38",
    classement: "C15.1",
    niveauEtoile: null,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Samedi", heure: "10:00" }, { jour: "Samedi", heure: "11:00" }],
  },
  {
    name: "Bernard Alice",
    age: "35",
    classement: "Non classé",
    niveauEtoile: 5,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Samedi", heure: "10:00" }, { jour: "Samedi", heure: "11:00" }],
  },
  {
    name: "Colin Nathan",
    age: "36",
    classement: "Non classé",
    niveauEtoile: 4,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Samedi", heure: "10:00" }, { jour: "Samedi", heure: "11:00" }],
  },
  {
    name: "Léa Renard",
    age: "12",
    classement: "C30.4",
    niveauEtoile: null,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: "Tom Renard",
    profPrefere: null,
    disponibilites: [{ jour: "Mercredi", heure: "14:00" }, { jour: "Mercredi", heure: "15:00" }, { jour: "Mercredi", heure: "16:00" }],
  },
  {
    name: "Tom Renard",
    age: "9",
    classement: "C30.6",
    niveauEtoile: null,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: "Léa Renard",
    profPrefere: null,
    disponibilites: [{ jour: "Mercredi", heure: "14:00" }, { jour: "Mercredi", heure: "15:00" }, { jour: "Mercredi", heure: "16:00" }],
  },
  {
    name: "Nathan Girard",
    age: "16",
    classement: "C30.1",
    niveauEtoile: null,
    preferenceGroupe: "groupe",
    jouerAvec: ["Louis Girard", "Adam Roux"],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Samedi", heure: "16:00" }, { jour: "Samedi", heure: "17:00" }, { jour: "Samedi", heure: "18:00" }],
  },
  {
    name: "Louis Girard",
    age: "15",
    classement: "C30.2",
    niveauEtoile: null,
    preferenceGroupe: "groupe",
    jouerAvec: ["Nathan Girard"],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Samedi", heure: "16:00" }, { jour: "Samedi", heure: "17:00" }, { jour: "Samedi", heure: "18:00" }],
  },
  {
    name: "Adam Roux",
    age: "16",
    classement: "C30",
    niveauEtoile: null,
    preferenceGroupe: "groupe",
    jouerAvec: ["Nathan Girard"],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Samedi", heure: "16:00" }, { jour: "Samedi", heure: "17:00" }, { jour: "Samedi", heure: "18:00" }],
  },
  {
    name: "Zoé Martin",
    age: "10",
    classement: "Non classé",
    niveauEtoile: 3,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Mercredi", heure: "17:00" }, { jour: "Mercredi", heure: "18:00" }, { jour: "Samedi", heure: "09:00" }, { jour: "Samedi", heure: "10:00" }],
  },
  {
    name: "Zoé Martin",
    age: "10",
    classement: "Non classé",
    niveauEtoile: 3,
    preferenceGroupe: "individuel",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Mercredi", heure: "17:00" }, { jour: "Mercredi", heure: "18:00" }, { jour: "Vendredi", heure: "16:00" }, { jour: "Vendredi", heure: "17:00" }],
  },
  {
    name: "Sarah Moreau",
    age: "34",
    classement: "C15.2",
    niveauEtoile: null,
    preferenceGroupe: "individuel",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: "Nick",
    disponibilites: [{ jour: "Mercredi", heure: "09:00" }, { jour: "Mercredi", heure: "10:00" }, { jour: "Mercredi", heure: "11:00" }],
  },
  {
    name: "Inès Fabre",
    age: "13",
    classement: "40/1",
    niveauEtoile: null,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Samedi", heure: "12:00" }, { jour: "Samedi", heure: "13:00" }],
  },
  {
    name: "Théo Blanc",
    age: "12",
    classement: "Non classé",
    niveauEtoile: 3,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [],
  },
  {
    name: "Rose Fontaine",
    age: "11",
    classement: "Non classé",
    niveauEtoile: 2,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Vendredi", heure: "17:00" }],
  },
  {
    name: "Sacha Perrin",
    age: "14",
    classement: "C30.3",
    niveauEtoile: null,
    preferenceGroupe: "individuel",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: "Fabio",
    disponibilites: [{ jour: "Vendredi", heure: "16:00" }, { jour: "Vendredi", heure: "17:00" }],
  },
  {
    name: "Mathis Renard",
    age: "10",
    classement: "Non classé",
    niveauEtoile: 2,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Mercredi", heure: "14:00" }, { jour: "Mercredi", heure: "15:00" }],
  },
  {
    name: "Alice Colin",
    age: "10",
    classement: "Non classé",
    niveauEtoile: 2,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Mercredi", heure: "14:00" }, { jour: "Mercredi", heure: "15:00" }],
  },
  {
    name: "Ethan Faure",
    age: "9",
    classement: "Non classé",
    niveauEtoile: 1,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Mercredi", heure: "14:00" }, { jour: "Mercredi", heure: "15:00" }],
  },
  {
    name: "Marie-Claire Dupont-Martin",
    age: "41",
    classement: "B0",
    niveauEtoile: null,
    preferenceGroupe: "groupe",
    jouerAvec: [],
    memeHoraireAvec: null,
    profPrefere: null,
    disponibilites: [{ jour: "Samedi", heure: "12:00" }, { jour: "Samedi", heure: "13:00" }],
  },
];

async function seedTestStudents(pool) {
  const insertedIds = [];
  for (const s of TEST_STUDENTS) {
    const id = uid();
    await pool.query(
      `INSERT INTO students (id, name, age, classement, niveau_etoile, preference_groupe, jouer_avec, terrain_adjacent_avec, prof_prefere)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
      [id, s.name, s.age, s.classement, s.niveauEtoile, s.preferenceGroupe, JSON.stringify(s.jouerAvec), s.memeHoraireAvec, s.profPrefere]
    );
    for (const d of s.disponibilites) {
      await pool.query(
        'INSERT INTO student_disponibilites (id, student_id, jour, heure) VALUES ($1, $2, $3, $4)',
        [uid(), id, d.jour, d.heure]
      );
    }
    insertedIds.push(id);
  }
  console.log(`${insertedIds.length} participants de test insérés.`);
  return insertedIds;
}

module.exports = { seedTestStudents };